main_override:
  total_time: 1.0

pushpull_override:
  amp: 200
  nmodes: 500

pupilstop_override:
  tag:               'asm_v30dx_197pixels_optshift'

pyr_im_calibrator_override: 
  im_tag:    'pyr3.0_40x40_lbti_synim'
  overwrite: true
  nmodes: 500

dm_override:
  ifunc_object:   'asm_v30dx_lbti_ifunc_optshift' 

data_store:
  class:             'DataStore'
  store_dir:         '/raid1/mmenessini/results/SOUL/KLv30dx/scratch_synim'
  create_tn: false
  inputs:
    input_list: ['ccd-ocam.out_pixels','dm_ef-dm.out_layer']