# Synthetic interaction matrix in partial correction
# ================================================

# Push-pull command generator
pushpull:
  class:        'PushPullGenerator'
  nmodes:       600                         # Number of DM actuators
  amp:          200  
  ncycles:       70
  repeat_full_sequence: true
  outputs:   ['output']

# Interaction matrix calibrator
pyr_im_calibrator:
  class:     'ImCalibrator'
  nmodes:    600                         # Number of modes to calibrate
  im_tag:    'pyr3.0_s1.0_synim'            # Output IM filename
  overwrite: false                         # Overwrite existing files
  inputs:
    in_slopes:   'pyr_slopes.out_slopes'      # WFS slopes input
    in_commands: 'pushpull.output'        # Push-pull commands

# Override main simulation parameters
main_override:
  time_step: 0.001
  total_time: 84.0                # 600 modes × 2 (push+pull) × 0.000588s x 70 cycles

################################## ATMO RESIDUAL #####################################
seeing_random:
  class:             'RandomGenerator'
  amp:               0.0                 # Variation amplitude [arcsec]
  constant:          1.0                 # Mean seeing [arcsec]
  distribution:      'UNIFORM'           # 
  outputs: ['output']

# Random atmospheric phase generator
atmo_random:
  class:                'AtmoRandomPhase'
  simul_params_ref:     'main'
  L0:                   25               # [m] Outer scale
  source_dict_ref:      ['source_ngs']
  update_interval:      1200                 # Update after push-pull of all modes
  inputs:
    seeing:             'seeing_random.output'
    pupilstop:          'pupilstop'
  outputs:              ['out_source_ngs_ef']

# Modal decomposition of atmospheric phase
modal_analysis_random:
  class: 'ModalAnalysis'
  ifunc_inv_object: 'asm_v30dx_ifunc_shift_inv'
  nmodes: 649
  inputs:
    in_ef: 'atmo_random.out_source_ngs_ef'
  outputs: ['out_modes']

scale_random:
  class:  'BaseOperation'
  constant_mul_data: 'corr_vec_20260609_192600' #'correction_vector_20260506_092825' 
  inputs:
    in_value1: 'modal_analysis_random.out_modes'
  outputs: ['out_value']

# DM applying partial correction
dm_random:
  class: 'DM'
  simul_params_ref:  'main'
  ifunc_object:      'asm_v30dx_ifunc_shift'      # Our computed influence functions
  m2c_object:        'asm_v30dx_m2c'        # Modal-to-command matrix
  height:            0.0                # Ground-conjugated DM
  inputs:
    in_command: 'scale_random.out_value'
  outputs: ['out_layer']

atmo_pc:
  class: 'ElectricFieldCombinator'
  inputs:
    in_ef1: 'atmo_random.out_source_ngs_ef'    # Turbulence
    in_ef2: 'dm_random.out_layer'              # Partial correction
  outputs: ['out_ef']

ef_mode:
  class: 'ElectricFieldCombinator'
  inputs:
    in_ef1: 'atmo_pc.out_ef'    # Partially corrected turbulence
    in_ef2: 'dm.out_layer'      # Mode amplitudes
  outputs: ['out_ef']

######################################################################################

# Override DM to use calibration commands
dm_override:
  sign: 1                                 # Use positive sign for calibration (default is -1)
  ifunc_object:      'asm_v30dx_ifunc_shift'      # Our computed influence functions
  nmodes: 600                            # Use all modes for calibration
  inputs:
    in_command: 'pushpull.output'         # Connect to push-pull generator

pyr_override:
  mod_amp: 3.0
  inputs: 
    in_ef: 'ef_mode.out_ef'

pyr_slopes_override:
  pupdata_object:         'lbt_pupdata'   

# Disable noise for clean measurements
ocam_override:
  dt: 0.001
  photon_noise:   false                   # No photon noise
  readout_noise:  false                   # No read noise
  excess_noise:   false                   # No excess noise

# atmo_pc_modes:
#   class: 'ModalAnalysis'
#   ifunc_inv_object: 'asm_v30dx_kl_inv'
#   inputs:
#     in_ef: 'atmo_pc.out_ef'
#   outputs: ['out_modes']

# data_store_override:
#   class:             'DataStore'
#   store_dir:         '/raid1/mmenessini/results/SOUL/KLv30dx/scratch_synim'
#   create_tn: false
#   inputs:
#     input_list: ['ef_field-ef_mode.out_ef']

# Remove unnecessary objects during calibration
remove: ['atmo','seeing','wind_speed','wind_direction','atmo_modes', #'source_science',
        'dm_mode_res','filter','psf', 'ef_prop', 'prop','pyr_modalrec', 'gain_ramp'] #, 'bootstrap', 'concat_wfs_modes'
