# Synthetic interaction matrix in partial correction
# ================================================

# Push-pull command generator
pushpull:
  class:        'PushPullGenerator'
  nmodes:       500                         # Number of DM actuators
  amp:          50  
  ncycles:       40
  repeat_full_sequence: true
  # constant_amp: true
  outputs:   ['output']

# Interaction matrix calibrator
pyr_im_calibrator:
  class:     'ImCalibrator'
  nmodes:    500                         # Number of modes to calibrate
  im_tag:    'pyr3.0_s1.0_c20260506_092825_nofit_im'            # Output IM filename
  overwrite: false                         # Overwrite existing files
  inputs:
    in_slopes:   'pyr_slopes.out_slopes'      # WFS slopes input
    in_commands: 'pushpull.output'        # Push-pull commands

# Override main simulation parameters
main_override:
  total_time: 23.52                # 500 modes × 2 (push+pull) × 0.000588s x 40 cycles

################################## ATMO RESIDUAL #####################################
seeing_random:
  class:             'RandomGenerator'
  amp:               0.0                 # Variation amplitude [arcsec]
  constant:          1.0                 # Mean seeing [arcsec]
  distribution:      'UNIFORM'           # 
  outputs: ['output']

# Random atmospheric phase generator
atmo_random:
  class:                'AtmoRandomPhase'
  simul_params_ref:     'main'
  L0:                   25               # [m] Outer scale
  source_dict_ref:      ['source_ngs']
  update_interval:      1000                 # Update after push-pull of all modes
  inputs:
    seeing:             'seeing_random.output'
    pupilstop:          'pupilstop'
  outputs:              ['out_source_ngs_ef']

# Modal decomposition of atmospheric phase
atmo_random_modes:
  class: 'ModalAnalysis'
  ifunc_inv_object: 'asm_v30dx_kl_inv'
  nmodes: 648
  inputs:
    in_ef: 'atmo_random.out_source_ngs_ef'
  outputs: ['out_modes']

atmo_correction:
  class:  'BaseOperation'
  constant_mul_data: 'correction_vector_20260506_092825' 
  inputs:
    in_value1: 'atmo_random_modes.out_modes'
  outputs: ['out_value']

atmo_res:
  class:  'BaseOperation'
  sub: true
  inputs:
    in_value1: 'atmo_random_modes.out_modes'
    in_value2: 'atmo_correction.out_value'
  outputs: ['out_value']

pushpull_in_pc:
  class:  'BaseOperation'
  sub: true
  inputs:
    in_value1: 'atmo_res.out_value'
    in_value2: 'pushpull.output'
  outputs: ['out_value']

prop_override:
  class:             'AtmoPropagation'
  simul_params_ref:  'main'
  source_dict_ref:   ['source_ngs'] 
  inputs:
    common_layer_list: ['pupilstop']       # Pupil
  outputs:           ['out_source_ngs_ef'] 

ef_mode:
  class: 'ElectricFieldCombinator'
  inputs:
    in_ef1: 'prop.out_source_ngs_ef'    # Unaberrated calibration source
    in_ef2: 'dm.out_layer'              # Mode amplitudes
  outputs: ['out_ef']

######################################################################################

# Override DM to use calibration commands
dm_override:
  sign: 1                                 # Use positive sign for calibration (default is -1)
  nmodes: 500                            # Use all modes for calibration
  inputs:
    in_command: 'pushpull_in_pc.output'         # Connect to push-pull generator

pyr_override:
  inputs: 
    in_ef: 'ef_mode.out_ef'

# Disable noise for clean measurements
ocam_override:
  photon_noise:   false                   # No photon noise
  readout_noise:  false                   # No read noise
  excess_noise:   false                   # No excess noise

atmo_pc_modes:
  class: 'ModalAnalysis'
  ifunc_inv_object: 'asm_v30dx_kl_inv'
  inputs:
    in_ef: 'atmo_pc.out_ef'
  outputs: ['out_modes']

# Remove unnecessary objects during calibration
remove: ['atmo','seeing','wind_speed','wind_direction','atmo_modes', 'data_store', #'source_science',
        'dm_mode_res','filter','psf', 'ef_prop','pyr_modalrec'] #, 'bootstrap', 'concat_wfs_modes'
