# Synthetic interaction matrix in partial correction
# ================================================
pyr_sn:
  class: 'SnCalibrator'
  output_tag: 'pyr0.0_40x40_sn_pc'           # Output filename
  overwrite: false
  inputs:
    in_slopes: 'pyr_slopes.out_slopes'

# Override main simulation parameters
main_override:
  total_time: 0.588                # 1000 cycles × 0.000588s

################################## ATMO RESIDUAL #####################################
seeing_random:
  class:             'RandomGenerator'
  amp:               0.0                 # Variation amplitude [arcsec]
  constant:          1.0                 # Mean seeing [arcsec]
  distribution:      'UNIFORM'           # 
  outputs: ['output']

# Random atmospheric phase generator
atmo_random:
  class:                'AtmoRandomPhase'
  simul_params_ref:     'main'
  L0:                   25               # [m] Outer scale
  source_dict_ref:      ['source_ngs']
  # update_interval:      1000                 # Update after push-pull of all modes
  inputs:
    seeing:             'seeing_random.output'
    pupilstop:          'pupilstop'
  outputs:              ['out_source_ngs_ef']

# Modal decomposition of atmospheric phase
modal_analysis_random:
  class: 'ModalAnalysis'
  ifunc_inv_object: 'asm_v30dx_ifunc_inv'
  nmodes: 648
  inputs:
    in_ef: 'atmo_random.out_source_ngs_ef'
  outputs: ['out_modes']

scale_random:
  class:  'BaseOperation'
  constant_mul_data: 'correction_vector_20260506_092825' 
  inputs:
    in_value1: 'modal_analysis_random.out_modes'
  outputs: ['out_value']

# DM applying partial correction
dm_random:
  class: 'DM'
  simul_params_ref:  'main'
  ifunc_object:      'asm_v30dx_ifunc'      # Our computed influence functions
  m2c_object:        'asm_v30dx_m2c'        # Modal-to-command matrix
  height:            0.0                # Ground-conjugated DM
  inputs:
    in_command: 'scale_random.out_value'
  outputs: ['out_layer']

atmo_pc:
  class: 'ElectricFieldCombinator'
  inputs:
    in_ef1: 'atmo_random.out_source_ngs_ef'    # Turbulence
    in_ef2: 'dm_random.out_layer'              # Partial correction
  outputs: ['out_ef']


######################################################################################

pyr_override:
  inputs: 
    in_ef: 'atmo_pc.out_ef'

# Disable noise for clean measurements
ocam_override:
  photon_noise:   false                   # No photon noise
  readout_noise:  false                   # No read noise
  excess_noise:   false                   # No excess noise

# atmo_pc_modes:
#   class: 'ModalAnalysis'
#   ifunc_inv_object: 'asm_v30dx_kl_inv'
#   inputs:
#     in_ef: 'atmo_pc.out_ef'
#   outputs: ['out_modes']

# data_store_override:
#   inputs:
#     input_list: ['atmo_res-atmo_pc_modes.out_modes']

# Remove unnecessary objects during calibration
remove: ['atmo','seeing','wind_speed','wind_direction','atmo_modes', 'dm', #'data_store', #'source_science',
        'dm_mode_res','filter','psf', 'ef_prop', 'prop','pyr_modalrec'] #, 'bootstrap', 'concat_wfs_modes'
