# Synthetic interaction matrix in partial correction
# ================================================

# Push-pull command generator
pushpull:
  class:        'PushPullGenerator'
  nmodes:       10                         # Number of DM actuators
  amp:          10  
  ncycles:      40
  repeat_full_sequence: true
  outputs:   ['output']

# Interaction matrix calibrator
pyr_im_calibrator:
  class:     'ImCalibrator'
  nmodes:    10                         # Number of modes to calibrate
  im_tag:    'pyr3.0_10modes_resOPD'            # Output IM filename
  overwrite: true                         # Overwrite existing files
  inputs:
    in_slopes:   'pyr_slopes.out_slopes'      # WFS slopes input
    in_commands: 'pushpull.output'        # Push-pull commands

# Override main simulation parameters
main_override:
  total_time: 0.4704                # 10 modes × 2 (push+pull) × 0.000588s x 40 cycles

atmo_res:
  class: 'PhaseScreenCube'
  simul_params_ref: 'main'
  cube_object:     '20230507_030749_res_OPD'
  pixel_scale:       0.042639
  inputs:
    pupilstop: 'pupilstop'
  outputs: ['out_layer','out_ef']

atmo_pc:
  class: 'ElectricFieldCombinator'
  inputs:
    in_ef1: 'atmo_res.out_ef'    # Turbulence
    in_ef2: 'dm.out_layer'              # Partial correction
  outputs: ['out_ef']


######################################################################################

# Override DM to use calibration commands
dm_override:
  sign: 1                                 # Use positive sign for calibration (default is -1)
  nmodes: 10                            # Use all modes for calibration
  inputs:
    in_command: 'pushpull.output'         # Connect to push-pull generator

pyr_override:
  inputs: 
    in_ef: 'atmo_pc.out_ef'

# Disable noise for clean measurements
ocam_override:
  photon_noise:   false                   # No photon noise
  readout_noise:  false                   # No read noise
  excess_noise:   false                   # No excess noise

data_store_override:
  inputs:
    input_list: ['atmo_pc_phs-atmo_pc.out_ef','pc_slopes-pyr_slopes.out_slopes' ]

# Remove unnecessary objects during calibration
remove: ['atmo','seeing','wind_speed','wind_direction','atmo_modes', 'gain_ramp', 
        'dm_mode_res','filter','psf', 'ef_prop', 'prop', 'pyr_modalrec'] 
