# Main simulation parameters
main:
  class:             'SimulParams'
  root_dir:          '/raid1/mmenessini/calibration/EKARUS/'       # CalibManager root directory (all the data are in subdirectories)
  pixel_pupil:       160                   # Must match influence function computation
  pixel_pitch:       0.011375             # [m] Pitch of the pupil phase array (1.82m/120pix)
  total_time:        0.0005                   # [s] Total simulation running time
  time_step:         0.0005                 # [s] Simulation time step
  zenithAngleInDeg:  0.0                   # [deg] Zenith observation (0 means no airmass)
  display_server:    false                 # Disable for batch runs


# Atmospheric conditions
seeing:
  class:             'WaveGenerator'
  constant:          1.5                  # [arcsec]

wind_speed:
  class:             'WaveGenerator'
  constant:          [6.6, 5.9, 5.1, 4.5, 5.1, 8.3, 16.3, 30.2, 34.3, 17.5]    # [m/s] Multi-layer wind speeds

wind_direction:
  class:             'WaveGenerator'
  constant:          [38.0, 34.0, 54.0, 42.0, 68.0, 48.0, -102.0, -83.0, -77.0, 34.0] # [deg] Wind directions for each layer


# Natural guide star for WFS
source_ngs:
  class:             'Source'
  polar_coordinates: [0.0, 0.0]            # [arcsec, deg] On-axis NGS
  height:            .inf                  # Infinite height (star)
  magnitude:         1.0                   # R-band magnitude (bright NGS)
  wavelengthInNm:    700                   # [nm] R-band for WFS

# Telescope pupil geometry
pupilstop:
  class:             'Pupilstop'
  tag:               'Copernico_Pupil_160pixels'

# Multi-layer atmospheric model
atmo:
  class:             'AtmoEvolution'
  simul_params_ref:  'main'
  L0:                25.0                   # [m] Outer scale
  heights:           [110, 238, 402, 728, 1381, 2686, 5296, 9066, 12836, 16136] # [m] Ground, mid, high layers at 0 zenith angle
  Cn2:               [0.59, 0.02, 0.04, 0.06, 0.01, 0.05, 0.09, 0.04, 0.05, 0.05]        # Cn2 fractions (sum = 1.0)
  fov:               0.0                    # [arcsec] Field of view
  inputs:
    seeing:          'seeing.output'
    wind_speed:      'wind_speed.output'
    wind_direction:  'wind_direction.output'
  outputs:           ['layer_list']
  
# Atmospheric propagation
prop:
  class:             'AtmoPropagation'
  simul_params_ref:  'main'
  source_dict_ref:   ['source_ngs'] 
  inputs:
    atmo_layer_list: ['atmo.layer_list']
    common_layer_list: ['pupilstop']       # Pupil
  outputs:           ['out_source_ngs_ef'] 

ef_prop:
  class: 'ElectricFieldCombinator'
  inputs:
    in_ef1: 'prop.out_source_ngs_ef'    # Turbulence
    in_ef2: 'dm.out_layer:-1'          # DM1 correction
  outputs: ['out_ef']

########################### PWFS ##############################
pyr:
  class:             'ModulatedPyramid'
  simul_params_ref:  'main'
  pup_diam:          37.                     # Pupil diameter in subaps.
  pup_dist:          60.                     # Separation between pupil centers in subaps.
  pyr_tlt_coeff:     [[1.1471709257142857, 1.0876296414285715, 1.1665203742857142, 1.1357142857142857], 
                      [1.075, 0.9702654842857144, 1.0096486014285715, 0.95]]
  fov:               8.8                     # Requested field-of-view [arcsec]
  mod_amp:           5.0                     # Modulation radius (in lambda/D units)
  output_resolution: 240                      # Output sampling [usually corresponding to CCD pixels]
  wavelengthInNm:    700                     # [nm] Pyramid wavelength
  inputs:
    in_ef: 'ef_prop.out_ef'

ocam:
  class:             'CCD'
  simul_params_ref:  'main'
  size:              [240,240]            # Total detector size
  dt:                0.0005              # [s] Integration time (2000 fps)
  bandw:             300                   # [nm]
  photon_noise:      true                  # Enable photon noise
  readout_noise:     true                  # Enable read noise
  excess_noise:      true                  # Enable excess noise
  readout_level:     0.4                   # [e-/pix/frame] Read noise level
  emccd_gain:        600                   # EMCCD gain factor
  quantum_eff:       0.06                   # QE x transmission
  inputs:
    in_i:            'pyr.out_i' 
  outputs:           ['out_pixels']

pyr_slopes:
  class:                  'PyrSlopec'
  pupdata_object:         'pyr_pupdata_onsky'           
  slopes_from_intensity:  true
  inputs:
    in_pixels:        'ocam.out_pixels'
  outputs:           ['out_slopes']

pyr_modalrec:
  class:             'Modalrec'
  recmat_object:     'pyr5.0_40x40_400modes_rec'        
  inputs:
    in_slopes:       'pyr_slopes.out_slopes'
  outputs:           ['out_modes']

filter: 
  class:             'Integrator'
  delay:             1.5                     # Temporal delay in time steps
  int_gain:          [1.0] #[0.7,0.6,0.2] #
  # ff:                [1.0,0.99,0.95]
  n_modes:           [400] #[2,120,278] #
  inputs:
      delta_comm:  'pyr_modalrec.out_modes' #

dm:
  class:             'DM'
  simul_params_ref:  'main'
  ifunc_object:      'reordered_unobs_DM468_ifunc'  # Measured Influence functions
  m2c_object:        'M2C_KL_OOPAO'                 # OOPAO M2C
  # ifunc_object:      'simul_unobs_DM468_ifunc'      # Simulated Influence functions
  # m2c_object:        'simul_unobs_DM468_m2c'        # Synthetic Modal-to-command matrix
  height:            0                # Ground-conjugated DM
  nmodes:            400
  inputs:
    in_command:      'filter.out_comm'
  outputs:           ['out_layer']


##################### POST-PROCESSING #####################
psf:
  class:             'PSF'
  simul_params_ref:  'main'
  wavelengthInNm:    650                 # [nm] visible
  nd:                4                    # 4x padding for PSF
  start_time:        0.0                  # Start PSF integration after 500ms
  # verbose: true
  inputs:
    in_ef:           'ef_prop.out_ef'
  outputs:           ['out_psf', 'out_std_psf', 'out_sr']
 
dm_mode_res:
  class:            'ModalAnalysis'
  ifunc_inv_object: 'reordered_unobs_DM468_kl_inv'
  # ifunc_inv_object: 'simul_unobs_DM468_kl_inv'
  inputs:
    in_ef: ['ef_prop.out_ef']
  outputs: ['out_modes']

atmo_modes:
  class:            'ModalAnalysis'
  ifunc_inv_object: 'reordered_unobs_DM468_kl_inv'
  # ifunc_inv_object: 'simul_unobs_DM468_kl_inv'
  inputs:
    in_ef: ['prop.out_source_ngs_ef']
  outputs: ['out_modes']

# Data store for results
data_store:
  class:             'DataStore'
  store_dir:         '/raid1/mmenessini/results/EKARUS'             # Data result directory: 'store_dir'/TN/
  inputs:
    input_list: [
                  # 'atmo_phase-ef_prop.out_ef',
                  'sr-psf.out_sr',
                  # 'psf-psf.out_psf',
                  # 'psf_std-psf.out_std_psf',
                  'atmo_res-atmo_modes.out_modes',
                  'dm_res-dm_mode_res.out_modes',
                  'dm_cmd-filter.out_comm',
                  'pyr_modes-pyr_modalrec.out_modes',
                  # 'ccd-ocam.out_pixels',
                  ]

