
# Main simulation parameters
main_override:
  total_time:        4.0                   # [s] Total simulation running time
  time_step:         0.0005                 # [s] Simulation time step

# Atmospheric conditions
seeing_override:
  constant:          1.5                  # [arcsec]

ef_prop2:
  class: 'ElectricFieldCombinator'
  inputs:
    in_ef1: 'ef_prop.out_ef'    # Turbulence
    in_ef2: 'dm2.out_layer:-1'          # DM1 correction
  outputs: ['out_ef']


########################### PWFS ##############################
pyr2:
  class:             'ModulatedPyramid'
  simul_params_ref:  'main'
  pup_diam:          20.                     # Pupil diameter in subaps.
  pup_dist:          30.                     # Separation between pupil centers in subaps.
  fov:               8.0                     # Requested field-of-view [arcsec]
  mod_amp:           0.0                     # Modulation radius (in lambda/D units)
  output_resolution: 120                      # Output sampling [usually corresponding to CCD pixels]
  wavelengthInNm:    1450                     # [nm] Pyramid wavelength
  inputs:
    in_ef: 'ef_prop2.out_ef' #'prop.out_source_ngs_ef'

ocam2:
  class:             'CCD'
  simul_params_ref:  'main'
  size:              [120,120]            # Total detector size
  dt:                0.0005              # [s] Integration time (2000 fps)
  bandw:             300                   # [nm]
  photon_noise:      true                  # Enable photon noise
  readout_noise:     true                  # Enable read noise
  excess_noise:      true                  # Enable excess noise
  readout_level:     0.5                   # [e-/pix/frame] Read noise level
  emccd_gain:        600                   # EMCCD gain factor
  quantum_eff:       0.06                   # QE x transmission
  inputs:
    in_i:            'pyr2.out_i' 
  outputs:           ['out_pixels']

pyr_slopes2:
  class:                  'PyrSlopec'
  pupdata_object:         'pyr_pupdata_20x20'           
  sn_object:              'pyr0.0_20x20_sn' # Commented during calibration
  slopes_from_intensity:  true
  inputs:
    in_pixels:        'ocam2.out_pixels'
  outputs:           ['out_slopes']

pyr_modalrec2:
  class:             'Modalrec'
  recmat_object:     'pyr0.0_20x20_220modes_rec'        
  inputs:
    in_slopes:       'pyr_slopes2.out_slopes'
  outputs:           ['out_modes']

filter2:  
  class:             'Integrator'
  simul_params_ref:  'main'
  delay:             1.0                     # Temporal delay in time steps
  int_gain:          [0.5] #[0.7,0.6,0.0] #
  ff:                [1.0]
  n_modes:           [220] #
  # class:                'IirFilter'
  # simul_params_ref:     'main'
  # delay:                1 # Total temporal delay in time steps is this value +1
  # iir_filter_data_object:  'ekarusiir_220modes_exc0_pow1.5'
  inputs:
    delta_comm: 'pyr_modalrec2.out_modes' #'concat_wfs_modes.out_value' 
  #   gain_mod: 'gain_ramp.output'
  # outputs:  ['out_comm']

# gain_ramp:
#   class:             'ScheduleGenerator'
#   scheduled_values: [[0.2],[0.1]]
#   modes_per_group: [220]
#   scheduled_times: [0.01]

dm2:
  class:             'DM'
  simul_params_ref:  'main'
  ifunc_object:      'DM468_ifunc' #'dm468_ifunc'      # Influence functions
  m2c_object:        'DM468_m2c' #'dm468_m2c'        # Modal-to-command matrix
  height:            0                # Ground-conjugated DM
  nmodes:            220
  inputs:
    in_command:      'filter2.out_comm'
  outputs:           ['out_layer']

###########################################################
##################### POST-PROCESSING #####################
coro_psf:
  class:             'PsfCoronagraph'
  simul_params_ref:  'main'
  wavelengthInNm:    1450                 # [nm] visible
  nd:                4                   # 4x padding for PSF
  start_time:        0.5                 # Start PSF integration after 500ms
  verbose: false
  compute_profile_metrics: true
  inputs:
    in_ef:           'ef_prop2.out_ef' 


# psf2:
#   class:             'PSF'
#   simul_params_ref:  'main'
#   wavelengthInNm:    750                 # [nm] visible
#   nd:                4                    # 4x padding for PSF
#   start_time:        0.5                  # Start PSF integration after 500ms
#   verbose: true
#   inputs:
#     in_ef:           'ef_prop2.out_ef'
#   outputs:           ['out_psf', 'out_std_psf', 'out_sr']

dm2_mode_res:
  class:            'ModalAnalysis'
  ifunc_inv_object: 'DM468_kl_inv'
  inputs:
    in_ef: ['ef_prop2.out_ef']
  outputs: ['out_modes']


# Data store for results
data_store_override:
  inputs:
    input_list: [                 
                  'atmo_phase-ef_prop2.out_ef',
                  'sr-psf.out_sr',
                  'coro_psf_int-coro_psf.out_int_coronagraph_psf_profile',
                  'coro_psf-coro_psf.out_std_coronagraph_psf_profile',
                  # 'psf-psf.out_psf',
                  # 'psf_std-psf.out_std_psf',
                  'atmo_res-atmo_modes.out_modes',
                  'dm2_res-dm2_mode_res.out_modes',
                  'dm_res-dm_mode_res.out_modes',
                  'dm_cmd-filter.out_comm',
                  'pyr_modes-pyr_modalrec.out_modes',
                  # 'ccd-ocam.out_pixels',
                  ]

# remove: ['']
