# this is the block that generates the pupil geometry file used by the Pyramid WFS
# as a function of a single frame of the Pyramid WFS
pyr_pupdata:
  class: 'PyrPupdataCalibrator'
  thr1: 0.1
  thr2: 0.4
  display_debug: True
  output_tag:        'pyr0.0_12x12_pupdata'
  overwrite: false
  inputs:
    in_i: 'pyr0.out_i'

pyr_override:
  mod_amp:           20.0   # Modulation radius (in lambda/D units)
  inputs:
    in_ef: 'prop.out_source_ngs_ef'


main_override:
  total_time:  0.0005

# Remove unnecessary components to avoid issues and speed up the calibration
remove: ['atmo', 'seeing', 'wind_direction', 'wind_speed', 'cred1', 'pyr_slopes', 'dm',
         'filter', 'ef_prop', 'dm_mode_res', 'ocam2','coro_psf',
           'data_store', 'psf', 'pyr_modalrec', 'atmo_modes']
# remove: ['atmo', 'seeing', 'wind_direction', 'wind_speed', 'cred1', 'pyr_slopes', 'dm1','dm2',
#          'filter1',  'filter2','ef_prop','first_stage_prop', 'dm1_mode_res', 'dm2_mode_res', 
#          'cred2', 'pyr0', 'pyr0_slopes', 'coro_psf',
#            'data_store', 'psf', 'pyr_modalrec', 'pyr0_modalrec','atmo_mode_res']