# Interaction Matrix and Reconstructor Calibration
# ================================================

# Push-pull command generator
pushpull:
  class:        'PushPullGenerator'
  nmodes:       1821                         # Number of DM actuators
  amp:          15   # was 5!
  # constant_amp: true
  outputs:   ['output']

zwfs_im_calibrator:
  class:     'ImCalibrator'
  nmodes:    1821                         # Number of modes to calibrate
  im_tag:    'z1.5wfs_1821modes_12x12_im'            # Output IM filename
  overwrite: false                         # Overwrite existing files
  inputs:
    in_slopes:   'zwfs_slopes.out_slopes'      # WFS slopes input
    in_commands: 'pushpull.output'        # Push-pull commands

# Override main simulation parameters
main_override:
  time_step: 0.0005
  total_time: 1.821                 # 1821 modes × 2 (push+pull) × 0.0005s

# Disable atmosphere for clean calibration
prop_override:
  source_dict_ref:   ['source_ngs']
  inputs:
    common_layer_list: ['pupilstop', 'dm.out_layer']  # Only pupil + DM
  outputs:           ['out_source_ngs_ef']

# Override DM to use calibration commands
dm_override:
  sign: 1                                 # Use positive sign for calibration (default is -1)
  nmodes: 1821                            # Use all modes for calibration
  inputs:
    in_command: 'pushpull.output'         # Connect to push-pull generator

zwfs_override:
  fft_res: 16.0
  spot_radius_lambda: 0.750                     # Spot RADIUS in λ/D units
  inputs: 
    in_ef: 'prop.out_source_ngs_ef'

# Disable noise for clean measurements
cred1_override:
  dt: 0.0005
  photon_noise:   false                   # No photon noise
  readout_noise:  false                   # No read noise
  excess_noise:   false                   # No excess noise

# Remove unnecessary objects during calibration
remove: ['atmo','seeing','wind_speed','wind_direction','data_store','atmo_modes', #'source_science','zwfs_modalrec'
        'dm_mode_res','filter','psf', 'coro_psf', 'ef_prop','zwfs_modalrec', ] #, 'bootstrap', 'concat_wfs_modes'
