pyr_override:
  pup_diam: 12.0
  pup_dist: 16.0
  mod_amp: 0.0
pyr_modalrec_override:
  recmat_object: 'pyr0.0_12x12_50modes_rec'
pyr_slopes_override:
  pupdata_object: 'pyr_pupdata_12x12'
seeing_random_override:
  constant: 1.5
dm_perfect_override:
  nmodes: 1200
modal_analysis_override:
  nmodes: 1200
source_ngs_override:
  magnitude: 5.0
pyr_sn_override:
  output_tag: 'pyr0.0_12x12_s1.50_1200modes_sn'
data_store_override:
  store_dir: /raid1/mmenessini/calibration/RISTRETTOunobs/scratch_aliasing
  create_tn: false
  inputs:
    input_list: ['pyr_frames-cred1.out_pixels', 'pyr_modes-pyr_modalrec.out_modes',
      'slopes-pyr_slopes.out_slopes']
